apiVersion: v1
kind: ConfigMap
metadata:
  name: fabric-ca-signing-config
  namespace: {{ $.Values.metadata.namespace }}
data:
  signing.yaml: |
    signing:
        default:
          usage:
            - digital signature
          expiry: 87600h
        profiles:
          ca:
             usage:
               - cert sign
               - crl sign
             expiry: 87600h
             caconstraint:
               isca: true
               maxpathlen: 0
          tls:
             usage:
                - signing
                - key encipherment
                - server auth
                - client auth
                - key agreement
             expiry: 87600h