apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-charlesfortchannel-trustee
  namespace: trustee-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-charlesfortchannel-trustee
  chart:
    git: git@github.com:sivaramkannan/baf-intain-fork.git
    ref: umbprod
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: trustee-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.trustee-net:7051
      localmspid: trusteeMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://umbprod.westus2.cloudapp.azure.com:8200
      authpath: devtrustee-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/trustee-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/trustee-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: charlesfortchannel      
    orderer:
      address: orderer1.intain-net:7050
    anchorstx: |-
      Ct4CCiAKHggCGgYIgNDBlgYiEmNoYXJsZXNmb3J0Y2hhbm5lbBK5Agq2AgoSY2hhcmxlc2ZvcnRj
      aGFubmVsEmMSYQoLQXBwbGljYXRpb24SUggBEk4KCnRydXN0ZWVNU1ASQBoHCgNNU1ASACILCgdS
      ZWFkZXJzEgAiCwoHV3JpdGVycxIAIgoKBkFkbWlucxIAIg8KC0VuZG9yc2VtZW50EgAaugEStwEK
      C0FwcGxpY2F0aW9uEqcBCAESogEKCnRydXN0ZWVNU1ASkwEIARpHCgtBbmNob3JQZWVycxI4Ei4K
      LAoncGVlcjAudHJ1c3RlZS1uZXQudW1icHJvZC5pbnRhaW5hYnMuY29tEPtBGgZBZG1pbnMaBwoD
      TVNQEgAiCwoHUmVhZGVycxIAIgsKB1dyaXRlcnMSACIKCgZBZG1pbnMSACIPCgtFbmRvcnNlbWVu
      dBIAKgZBZG1pbnM=

