apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: trustee-net
secrets:
- name: default
---
---
apiVersion: v1
kind: Secret
metadata:
  name: default
  namespace: trustee-net
  annotations:
    kubernetes.io/service-account.name: default
type: kubernetes.io/service-account-token
