apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: trustee-net
secrets:
- name: vault-auth  
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth
  namespace: trustee-net
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token
